# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

LLVM_COMPAT=( 18 19 20 21 22 )
# highest rust-version among the vendored crates; edition 2024 needs 1.85
RUST_MIN_VER="1.89.0"
# pinned by FLUTTER_VERSION in .github/workflows/ci.yml; re-check it on every bump
FLUTTER_PV="3.41.9"

inherit cargo desktop flutter-app xdg

DESCRIPTION="Cross-platform alternative to AirDrop for the local network"
HOMEPAGE="https://localsend.org https://github.com/localsend/localsend"

# Generated by pubspec2ebuild from the workspace pubspec.lock as pub rewrites it
# after support/scripts/remove_proprietary_dependencies.sh (only the four
# in_app_purchase entries drop out), merged with cargokit's
# build_tool/pubspec.lock, which pub resolves separately.
PUB_HOSTED=(
	"_fe_analyzer_shared 64.0.0 eb376e9acf6938204f90eb3b1f00b578640d3188b4c8a8ec054f9f479af8d051"
	"_fe_analyzer_shared 93.0.0 8d7ff3948166b8ec5da0fbb5962000926b8e02f2ed9b3e51d1738905fbd4c98d"
	"adaptive_number 1.0.0 3a567544e9b5c9c803006f51140ad544aedc79604fd4f3f2c1380003f97c1d77"
	"analyzer 10.0.1 de7148ed2fcec579b19f122c1800933dfa028f6d9fd38a152b04b1516cec120b"
	"analyzer 6.2.0 69f54f967773f6c26c7dcb13e93d7ccee8b17a641689da39e878d5cf13b06893"
	"animated_vector 0.2.2 f1beb10e6fcfd8bd15abb788e20345def786d1c7391d7c1426bb2a1f2adf2132"
	"animated_vector_annotations 0.2.2 07c1ea603a2096f7eb6f1c2b8f16c3c330c680843ea78b7782a3217c3c53f979"
	"ansicolor 2.0.3 50e982d500bc863e1d703448afdbf9e5a72eb48840a4f766fa361ffd6877055f"
	"archive 4.0.9 a96e8b390886ee8abb49b7bd3ac8df6f451c621619f52a26e815fdcf568959ff"
	"args 2.4.2 eef6c46b622e0494a36c5a12d10d77fb4e855501a91c1b9ef9339326e58f0596"
	"args 2.7.0 d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04"
	"assorted_layout_widgets 11.0.0 86c6942f569f7f70bfb03b9cb0ada9bf5aee72264aaefdb0e2be0fbee70cfb06"
	"async 2.11.0 947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
	"async 2.13.1 e2eb0491ba5ddb6177742d2da23904574082139b07c1e33b8503b9f46f3e1a37"
	"boolean_selector 2.1.1 6cfb5af12253eaf2b368f07bacc5a80d1301a071c73360d746b7f2e32d762c66"
	"boolean_selector 2.1.2 8aab1771e1243a5063b8b0ff68042d67334e3feab9e95b9490f9a6ebf73b42ea"
	"build 4.0.7 45d14a0fb23e018d8287c32fc98d726ce466b231928ed9b9200f29bd3ccd39ae"
	"build_cli_annotations 2.1.1 e563c2e01de8974566a1998410d3f6f03521788160a02503b0b1f1a46c7b3d95"
	"build_config 1.3.2 94eaf6708fe64408c632ef2689ca3777b112f9421306ccf4f8c84d7c5c9f83f8"
	"build_daemon 4.1.5 79e05eaf15a48d7230b053a4363b8eaac0cc234bbd0134c3229455481f55cbc6"
	"build_runner 2.15.1 5367e521935b102bdf1e735d2aab461e36b2edca6517662d088dd04cc39f8d16"
	"built_collection 5.1.1 376e3dd27b51ea877c28d525560790aee2e6fbb5f20e2f85d5081027d94e2100"
	"built_value 8.12.7 31b24be6615ec7fcf70b3aa5a7469fe35826485e639a16dd7eb83ba30e4cc6a8"
	"characters 1.4.1 faf38497bda5ead2a8c7615f4f7939df04333478bf32e4173fcb06d428b5716b"
	"checked_yaml 2.0.4 959525d3162f249993882720d52b7e0c833978df229be20702b33d48d91de70f"
	"cli_config 0.2.0 ac20a183a07002b700f0c25e61b7ee46b23c309d76ab7b7640a028f18e4d99ec"
	"clock 1.1.2 fddb70d9b5277016c77a80201021d40a2247104d9f4aa7bab7157b7e3f05b84b"
	"code_assets 1.2.1 bf394f466ba9205f1812a0433b392d6af280f155f56651eda7c18cc32ed493b8"
	"code_builder 4.11.1 6a6cab2ba4680d6423f34a9b972a4c9a94ebe1b62ecec4e1a1f2cba91fd1319d"
	"collection 1.18.0 ee67cb0715911d28db6bf4af1026078bd6f0128b07a5f66fb2ed94ec6783c09a"
	"collection 1.19.1 2f5709ae4d3d59dd8f7cd309b4e023046b57d8a6c82130785d2b0e5868084e76"
	"color 3.0.0 ddcdf1b3badd7008233f5acffaf20ca9f5dc2cd0172b75f68f24526a5f5725cb"
	"connectivity_plus 7.3.1 762c99f890ca8bf87f7337236f99edd42793843bc6c3631da294a76653a54bd0"
	"connectivity_plus_platform_interface 2.1.0 3c09627c536d22fd24691a905cdd8b14520de69da52c7a97499c8be5284a32ed"
	"convert 3.1.1 0f08b14755d163f6e2134cb58222dd25ea2a2ee8a195e53983d57c075324d592"
	"convert 3.1.2 b30acd5944035672bc15c6b7a8b47d773e41e2f17de064350988c5d02adb1c68"
	"coverage 1.15.1 956a3de0725ca232ad353565a8290d3357592bf4250f6f298a185e2d949c5d3d"
	"coverage 1.6.3 2fb815080e44a09b85e0f2ca8a820b15053982b2e714b59267719e8a9ff17097"
	"cross_file 0.3.5+4 92c9c43c383bfa1c32079d3bc492d55d6d4318044b7b47edaff8971cbb555c51"
	"crypto 3.0.3 ff625774173754681d66daaf4a448684fb04b78f902da9cb3d308c19cc5e8bab"
	"crypto 3.0.7 c8ea0233063ba03258fbcf2ca4d6dadfefe14f02fab57702265467a19f27fadf"
	"csslib 1.0.2 09bad715f418841f976c77db72d5398dc1253c21fb9c0c7f0b0b985860b2d58e"
	"dart_mappable 4.8.0 960746478faaa68ed6b9d3c6fd03c87c7b8614e6c33e75fe1b0c6d7a60adcf29"
	"dart_mappable_builder 4.8.0 eb89efebad96bae52333ae4bd6b8fdcfb44c921f8a38f44893f2c72ed15c860c"
	"dart_style 3.1.7 29f7ecc274a86d32920b1d9cfc7502fa87220da41ec60b55f329559d5732e2b2"
	"dartx 1.2.0 8b25435617027257d43e6508b5fe061012880ddfdaa75a71d607c3de2a13d244"
	"dbus 0.7.13 792974a4007974fbc5c1b5433eb2330a9db3e368c3f906253af4c007d0f49a91"
	"desktop_drop 0.7.1 aa1e797255bfbc76f9eb5aa4f61e5b68dbf69962ab1be6495816d2f251bc0d1f"
	"device_info_plus 12.4.0 b4fed1b2835da9d670d7bed7db79ae2a94b0f5ad6312268158a9b5479abbacdd"
	"device_info_plus_platform_interface 7.0.3 e1ea89119e34903dca74b883d0dd78eb762814f97fb6c76f35e9ff74d261a18f"
	"dynamic_color 1.8.1 43a5a6679649a7731ab860334a5812f2067c2d9ce6452cf069c5e0c25336c17c"
	"ed25519_edwards 0.3.1 6ce0112d131327ec6d42beede1e5dfd526069b18ad45dcf654f15074ad9276cd"
	"extended_image 10.1.0 e81d801cd692921f152834e01f39bba8b3d6302c48ad420d499c6062a7e24737"
	"extended_image_library 5.0.1 1f9a24d3a00c2633891c6a7b5cab2807999eb2d5b597e5133b63f49d113811fe"
	"fake_async 1.3.3 5368f224a74523e8d2e7399ea1638b37aecfca824a3cc4dfdf77bf1fa905ac44"
	"ffi 2.2.0 6d7fd89431262d8f3125e81b50d3847a091d846eafcd4fdb88dd06f36d705a45"
	"file 6.1.4 1b92bec4fc2a72f59a8e15af5f52cd441e4a7860b49499d69dfa817af20e925d"
	"file 7.0.1 a3b4f84adafef897088c160faf7dfffb7696046cb13ae90b508c2cbc95d3b8d4"
	"file_picker 11.0.3 29cc1fdb20613876cc7afc529738c1c0f11a9ca159b010edad0c566ac330847e"
	"file_selector 1.1.0 bd15e43e9268db636b53eeaca9f56324d1622af30e5c34d6e267649758c84d9a"
	"file_selector_android 0.5.2+6 89243030ea4b3463fb402b44d5eeacc4ccb1c46a88870cb2a5080d693200c1ed"
	"file_selector_ios 0.5.3+5 e2ecf2885c121691ce13b60db3508f53c01f869fb6e8dc5c1cfa771e4c46aeca"
	"file_selector_linux 0.9.4 2567f398e06ac72dcf2e98a0c95df2a9edd03c2c2e0cacd4780f20cdf56263a0"
	"file_selector_macos 0.9.5 5e0bbe9c312416f1787a68259ea1505b52f258c587f12920422671807c4d618a"
	"file_selector_platform_interface 2.7.0 35e0bd61ebcdb91a3505813b055b09b79dfdc7d0aee9c09a7ba59ae4bb13dc85"
	"file_selector_web 0.9.5 73181fbc5257776d8ecaa6a94ab3c8e920ad143b9132a6d984a9271dfc6928d3"
	"file_selector_windows 0.9.3+5 62197474ae75893a62df75939c777763d39c2bc5f73ce5b88497208bc269abfd"
	"fixnum 1.1.0 25517a4deb0c03aa0f32fd12db525856438902d9c16536311e76cdc57b31d7d1"
	"fixnum 1.1.1 b6dc7065e46c974bc7c5f143080a6764ec7a4be6da1285ececdc37be96de53be"
	"flex_color_picker 3.8.0 a0979dd61f21b634717b98eb4ceaed2bfe009fe020ce8597aaf164b9eeb57aaa"
	"flex_seed_scheme 4.0.1 a3183753bbcfc3af106224bff3ab3e1844b73f58062136b7499919f49f3667e7"
	"flutter_displaymode 0.7.0 ecd44b1e902b0073b42ff5b55bf283f38e088270724cdbb7f7065ccf54aa60a8"
	"flutter_foreground_task 9.2.2 fc5c01a5e1b8f7bb51d0c737714f0c50440dbdf1aeddc5f8cbba313aa6fd4856"
	"flutter_gen_core 5.15.0 8ccb1f809642b34eb4857d8d7c4e5b41430a8cba8206177aae2ffe9d72b5eef3"
	"flutter_gen_runner 5.15.0 2b0fff517a75a14ed2eff749c1da2d6b8b568e542ad2b1c967356669a4c29bb2"
	"flutter_lints 6.0.0 3105dc8492f6183fb076ccf1f351ac3d60564bff92e20bfc4af9cc1651f4e7e1"
	"flutter_markdown 0.7.7+1 08fb8315236099ff8e90cb87bb2b935e0a724a3af1623000a9cec930468e0f27"
	"flutter_plugin_android_lifecycle 2.0.35 3854fe5e3bff0b113c658f260b90c95dea17c92db0f2addeac2e343dd9969785"
	"flutter_rust_bridge 2.12.0 e87d6b9ee934dcd24a128ccb2bd91905d2d5fe5c06245d6a8f5477d4907a437a"
	"freezed 3.2.5 f23ea33b3863f119b58ed1b586e881a46bd28715ddcc4dbc33104524e3434131"
	"freezed_annotation 3.1.0 7294967ff0a6d98638e7acb774aac3af2550777accd8149c90af5b014e6d44d8"
	"frontend_server_client 3.2.0 408e3ca148b31c20282ad6f37ebfa6f4bdc8fede5b74bc2f08d9d92b55db3612"
	"frontend_server_client 4.0.0 f64a0333a82f30b0cca061bc3d143813a486dc086b574bfb233b7c1372427694"
	"gal 2.3.3 f71e79840fe023a21f2f949771375444b6efcd34b9e625d5f4f5504971380a77"
	"github 9.17.0 9966bc13bf612342e916b0a343e95e5f046c88f602a14476440e9b75d2295411"
	"glob 2.1.2 0e7014b3b7d4dac1ca4d6114f82bf1782ee86745b9b42a92c9289c23d8a0ab63"
	"glob 2.1.3 c3f1ee72c96f8f78935e18aa8cecced9ab132419e8625dc187e1c2408efc20de"
	"graphs 2.3.2 741bbf84165310a68ff28fe9e727332eef1407342fca52759cb21ad8177bb8d0"
	"gsettings 0.2.8 1b0ce661f5436d2db1e51f3c4295a49849f03d304003a7ba177d01e3a858249c"
	"gtk 2.2.0 4ff85b2a16724029dd9e5bbb5a94b6918f9973f74ba571c949d2002801879cf5"
	"hashcodes 2.0.0 80f9410a5b3c8e110c4b7604546034749259f5d6dcca63e0d3c17c9258f1a651"
	"hex 0.2.0 4e7cd54e4b59ba026432a6be2dd9d96e4c5205725194997193bf871703b82c4a"
	"hooks 2.0.2 9a62a50b50b769a737bc0a8ff381f333529df3ab746b2f6b02e83760231455ba"
	"html 0.15.6 6d1264f2dffa1b1101c25a91dff0dc2daee4c18e87cd8538729773c073dbf602"
	"http 1.1.0 759d1a329847dd0f39226c688d3e06a6b8679668e350e2891a6474f8b4bb8525"
	"http 1.6.0 87721a4a50b19c7f1d49001e51409bddc46303966ce89a65af4f4e6004896412"
	"http_client_helper 3.0.0 8a9127650734da86b5c73760de2b404494c968a3fd55602045ffec789dac3cb1"
	"http_multi_server 3.2.1 97486f20f9c2f7be8f514851703d0119c3596d14ea63227af6f7a481ef2b2f8b"
	"http_multi_server 3.2.2 aa6199f908078bb1c5efb8d8638d4ae191aac11b311132c3ef48ce352fb52ef8"
	"http_parser 4.0.2 2aa08ce0341cc9b354a498388e30986515406668dbcc4f7c950c3e715496693b"
	"http_parser 4.1.2 178d74305e7866013777bab2c3d8726205dc5a4dd935297175b19a23a2e66571"
	"image 4.9.1 6300175e00616bbc832e2fc91bfa4d776af5402c81c7151bee6905bb08473c52"
	"image_picker 1.2.3 d8402284df184bc05f4a2210c6c23983b0720f4cd87cbd05c5390a78af602667"
	"image_picker_android 0.8.13+17 d5b3e1774af29c9ab00103afb0d4614070f924d2e0057ac867ec98800114793f"
	"image_picker_for_web 3.1.1 66257a3191ab360d23a55c8241c91a6e329d31e94efa7be9cf7a212e65850214"
	"image_picker_ios 0.8.13+6 b9c4a438a9ff4f60808c9cf0039b93a42bb6c2211ef6ebb647394b2b3fa84588"
	"image_picker_linux 0.2.2 1f81c5f2046b9ab724f85523e4af65be1d47b038160a8c8deed909762c308ed4"
	"image_picker_macos 0.2.2+1 86f0f15a309de7e1a552c12df9ce5b59fe927e71385329355aec4776c6a8ec91"
	"image_picker_platform_interface 2.11.1 567e056716333a1647c64bb6bd873cff7622233a5c3f694be28a583d4715690c"
	"image_picker_windows 0.2.2 d248c86554a72b5495a31c56f060cf73a41c7ff541689327b1a7dbccc33adfae"
	"image_size_getter 2.4.1 7c26937e0ae341ca558b7556591fd0cc456fcc454583b7cb665d2f03e93e590f"
	"intl 0.20.2 3df61194eb431efc39c4ceba583b95633a403f46c9fd341e550ce0bfa50e9aa5"
	"io 1.0.4 2ec25704aba361659e10e3e5f5d672068d332fc8ac516421d483a11e5cbd061e"
	"io 1.0.5 dfd5a80599cf0165756e3181807ed3e77daf6dd4137caaad72d0b7931597650b"
	"jni 1.0.3 f038e58b4dc2c9037f50e233175086337e0b305e356d28211bf55f21c504cbd3"
	"jni_flutter 1.0.2 7b717011ea40d04fd47c2731d3d1d36eb99eba3435c2753d62489e8c3c9991d5"
	"jni_util 1.0.0 1ba86da04a5f2bf18fde2edb235587e70c5b0fc5bd4ba955f46b00942c3fc35f"
	"js 0.6.7 f2c445dce49627136094980615a031419f7f3eb393237e4ecd97ac15dea343f3"
	"js 0.7.2 53385261521cc4a0c4658fd0ad07a7d14591cf8fc33abbceae306ddb974888dc"
	"json_annotation 4.12.0 2a743920d81b7910627f68ee2c9ac1fc0bfee32b9fc3403587d7c6791ca12f80"
	"json_annotation 4.8.1 b10a7b2ff83d83c777edba3c6a0f97045ddadd56c944e1a23a3fdf43a1bf4467"
	"leak_tracker 11.0.2 33e2e26bdd85a0112ec15400c8cbffea70d0f9c3407491f672a2fad47915e2de"
	"leak_tracker_flutter_testing 3.0.10 1dbc140bb5a23c75ea9c4811222756104fbcd1a27173f0c34ca01e16bea473c1"
	"leak_tracker_testing 3.0.2 8d5a2d49f4a66b49744b23b018848400d23e54caf9463f4eb20df3eb8acb2eb1"
	"lints 2.1.1 0a217c6c989d21039f1498c3ed9f3ed71b354e69873f13a8dfc3c9fe76f1b452"
	"lints 6.1.0 12f842a479589fea194fe5c5a3095abc7be0c1f2ddfa9a0e76aed1dbd26a87df"
	"local_hero 0.3.0 5c85451dd51ecd0e8d3656775fac9a6db82f296f200d9931217186d34fed6089"
	"logging 1.2.0 623a88c9594aa774443aa3eb2d41807a48486b5613e67599fb4c41c0ad47c340"
	"logging 1.3.0 c8245ada5f1717ed44271ed1c26b8ce85ca3228fd2ffdb75468ab01979309d61"
	"markdown 7.3.1 ee85086ad7698b42522c6ad42fe195f1b9898e4d974a1af4576c1a3a176cada9"
	"matcher 0.12.16 1803e76e6653768d64ed8ff2e1e67bea3ad4b923eb5c56a295c3e634bad5960e"
	"matcher 0.12.19 dc0b7dc7651697ea4ff3e69ef44b0407ea32c487a39fff6a4004fa585e901861"
	"material_color_utilities 0.13.0 9c337007e82b1889149c82ed242ed1cb24a66044e30979c44912381e9be4c48b"
	"matrix4_transform 4.0.1 1346e53517e3081d3e8362377be97e285e2bd348855c177eae2a18aa965cafa0"
	"menu_base 0.1.1 820368014a171bd1241030278e6c2617354f492f5c703d7b7d4570a6b8b84405"
	"meta 1.17.0 23f08335362185a5ea2ad3a4e597f1375e78bce8a040df5c600c8d3552ef2394"
	"meta 1.9.1 3c74dbf8763d36539f114c799d8a2d87343b5067e9d796ca22b5eb8437090ee3"
	"mime 1.0.4 e4ff8e8564c03f255408decd16e7899da1733852a9110a58fe6d1b817684a63e"
	"mime 2.0.0 41a20518f0cb1256669420fdba0cd90d21561e560ac240f26ef8322e45bb7ed6"
	"mockito 5.6.4 eff30d002f0c8bf073b6f929df4483b543133fcafce056870163587b03f1d422"
	"moform 0.2.11 6b45d11bf65149a68b6eb19f0ff3d805956d059a254b5ba8ca2267362d6a2717"
	"nanoid2 2.0.1 35b5048f836652a1d711db0d716bdee59fcaaa4c37792db8b3568da4f7feb2f9"
	"nested 1.0.0 03bac4c528c64c95c722ec99280375a6f2fc708eec17c7b3f07253b626cd2a20"
	"network_info_plus 7.0.0 2866dadcbee2709e20d67737a1556f5675b8b0cdcf2c1659ba74bc21bffede4f"
	"network_info_plus_platform_interface 2.0.2 7e7496a8a9d8136859b8881affc613c4a21304afeb6c324bcefc4bd0aff6b94b"
	"nm 0.5.0 2c9aae4127bdc8993206464fcc063611e0e36e72018696cd9631023a31b24254"
	"node_preamble 2.0.2 6e7eac89047ab8a8d26cf16127b5ed26de65209847630400f9aefd7cd5c730db"
	"objective_c 9.5.0 b7fb95a6d9a4f009edd63dc5ac69f07420b23a16161c6dd8660290b59c602e8e"
	"open_dir 0.0.2+1 a4884b00e5e5795a9b4b3d582ac6a66e9196795ed760dbc3c63b4837c70c5901"
	"open_dir_linux 0.0.2+1 566cd9e02403971be06af35e1abc8057a4f3f98888c1226042e96a2af333b8bc"
	"open_dir_macos 0.0.2 51fdc8c3a06c9d571b599b5901045ada23d1440b24c3052c0a66cf3ee4ac901b"
	"open_dir_platform_interface 0.0.2 ca189abb02d8e3320f9b2493b6d58e3a33f393d5eb4ccbbef02e0bc0fd393872"
	"open_dir_windows 0.0.2+1 ec48df32ce61adb6f6cede0330d13b0d89714d2ee2df198f32ecd520e3a5d250"
	"open_filex 4.7.0 9976da61b6a72302cf3b1efbce259200cd40232643a467aac7370addf94d6900"
	"package_config 2.1.0 1c5b77ccc91e4823a5af61ee74e6b972db1ef98c2ff5a18d3161c982a55448bd"
	"package_config 2.2.0 f096c55ebb7deb7e384101542bfba8c52696c1b56fca2eb62827989ef2353bbc"
	"package_info_plus 9.0.1 468c26b4254ab01979fa5e4a98cb343ea3631b9acee6f21028997419a80e1a20"
	"package_info_plus_platform_interface 3.2.1 202a487f08836a592a6bd4f901ac69b3a8f146af552bbd14407b6b41e1c3f086"
	"path 1.8.0 2ad4cddff7f5cc0e2d13069f2a3f7a73ca18f66abd6f5ecf215219cdb3638edb"
	"path 1.9.1 75cca69d1490965be98c73ceaea117e8a04dd21217b37b292c9ddbec0d955bc5"
	"path_parsing 1.1.0 883402936929eac138ee0a45da5b0f2c80f89913e6dc3bf77eb65b84b409c6ca"
	"path_provider 2.1.6 a7f4874f987173da295a61c181b8ee71dab59b332a486b391babf26a1b884825"
	"path_provider_android 2.3.1 69cbd515a62b94d32a7944f086b2f82b4ac40a1d45bebfc00813a430ab2dabcd"
	"path_provider_foundation 2.6.0 2a376b7d6392d80cd3705782d2caa734ca4727776db0b6ec36ef3f1855197699"
	"path_provider_linux 2.2.2 58c2005f147315b11e9b4a7bc889cd5203e250cba8e3f012dae259b4972b5c16"
	"path_provider_platform_interface 2.1.3 484838772624c3a4b94f1e44a3e19897fee738f2d5c4ce448443b0417f7c9dda"
	"path_provider_windows 2.3.0 bd6f00dbd873bfb70d0761682da2b3a2c2fccc2b9e84c495821639601d81afe7"
	"permission_handler 12.0.3 fe54465bcc62a4564c6e4db337bbaded6c0c0fa6e10487414436d163114784f6"
	"permission_handler_android 13.0.1 1e3bc410ca1bf84662104b100eb126e066cb55791b7451307f9708d4007350e6"
	"permission_handler_apple 9.6.1 f49cb15a064ea9d974fc7fbb302099353b7b170d07284e86e264561579e5bcf8"
	"permission_handler_html 0.1.4+1 6ea98b3f17f60d3b527f2647ed2ab4dc0f6bfe25b22cb1c363f5d8f62252f6ac"
	"permission_handler_platform_interface 4.4.0 a5c8a97ecf5616112a5b16d4b8e9ec0e5ae90ef63ac69c0d7b8ae240be760b23"
	"petitparser 5.4.0 cb3798bef7fc021ac45b308f4b51208a152792445cce0448c9a4ba5879dd8750"
	"petitparser 7.0.2 91bd59303e9f769f108f8df05e371341b15d59e995e6806aefab827b58336675"
	"photo_manager 3.12.0 2d00a785b501bf1e5f6180bbef772846e767be11d45d11112b63092ef54a419e"
	"photo_manager_image_provider 2.2.0 b6015b67b32f345f57cf32c126f871bced2501236c405aafaefa885f7c821e4f"
	"platform 3.1.6 5d6b1b0036a5f331ebc77c850ebc8506cbc1e9416c27e59b439f917a902a4984"
	"platform_linux 0.1.2+1 907b7c6da6ee6eea61cd1266b7bd72e2d5bbf7e85160221e8ac5583a44e7a1c7"
	"plugin_platform_interface 2.1.8 4820fbfdb9478b1ebae27888254d445073732dae3d6ea81f0b7e06d5dedc3f02"
	"pool 1.5.1 20fe868b6314b322ea036ba325e6fc0711a22948856475e2c2b6306e8ab39c2a"
	"pool 1.5.2 978783255c543aa3586a1b3c21f6e9d720eb315376a915872c61ef8b5c20177d"
	"posix 6.5.2 bc1bad54ad2b735816e31f8d4600cfde6c7839975085ddfbca48b6c9f7c4044e"
	"pretty_qr_code 3.6.0 474f8a4512113fba06f14a6ec9bbf42353b4e651d7a520e3096f2a9b6bbe7a8a"
	"provider 6.1.5+1 4e82183fa20e5ca25703ead7e05de9e4cceed1fbd1eadc1ac3cb6f565a09f272"
	"pub_semver 2.1.4 40d3ab1bbd474c4c2328c91e3a7df8c6dd629b79ece4c4bd04bee496a224fb0c"
	"pub_semver 2.2.0 5bfcf68ca79ef689f8990d1160781b4bad40a3bd5e5218ad4076ddb7f4081585"
	"pubspec_parse 1.5.0 0560ba233314abbed0a48a2956f7f022cce7c3e1e73df540277da7544cad4082"
	"qr 3.0.2 5a1d2586170e172b8a8c8470bbbffd5eb0cd38a66c0d77155ea138d3af3a4445"
	"record_use 0.6.0 2551bd8eecfe95d14ae75f6021ad0248be5c27f138c2ec12fcb52b500b3ba1ed"
	"refena 3.5.0 835e762692c85d0358563f720e076d43f6145388fd6884ddeb64f911a00c0078"
	"refena_flutter 3.5.0 4c20bfe96552f458ca97ad95a3faf48d77a588eaa6c64fba6a9b184ed5fd83cb"
	"refena_inspector 2.1.1 8fade1bc8a3aacf6333fe5b991f7bf11bd2e083ae6e2e1761a46539cfb181c56"
	"refena_inspector_client 2.1.1 988e55dd90603126551056a0a9da9662f0574a7bc6b6189586e1ea2205a4d22d"
	"routerino 0.8.1 1666d9946cb20e59c1bd9374f8796d90798796f1a7685950371e791dcd1d0e48"
	"screen_retriever 0.2.2 ace919117a7520c13a50a6259e60c4a0d4cbe98809468792a91b5c5adada2aa6"
	"screen_retriever_linux 0.2.2 7b52006a5ceae1f3d5af7f77188c3290d6e7d8ded16d99809bea84967c65c257"
	"screen_retriever_macos 0.2.2 a1489b99cce597c45a54b9aae1cd94c8d4705353b7e0bb2457a6e4de44e0ad8a"
	"screen_retriever_platform_interface 0.2.2 94a5535277510a63184ca178ce12a1449bc0b38618879aa1c18bf57369c5064a"
	"screen_retriever_windows 0.2.2 dafc6922b0bfbf1d48cf3ccbf519b4fff47bdcb820da1728ea6db675fecc9324"
	"serial_csv 0.5.2 2d62bb70cb3ce7251383fc86ea9aae1298ab1e57af6ef4e93b6a9751c5c268dd"
	"share_handler 0.0.22 76575533be04df3fecbebd3c5b5325a8271b5973131f8b8b0ab8490c395a5d37"
	"share_handler_android 0.0.11 caf555b933dc72783aa37fef75688c7b86bd6f7bc17d80fbf585bc42f123cc8d"
	"share_handler_ios 0.0.15 cdc21f88f336a944157a8e9ceb191525cee3b082d6eb6c2082488e4f09dc3ece"
	"share_handler_platform_interface 0.0.6 7a4df95a87b326b2f07458d937f2281874567c364b7b7ebe4e7d50efaae5f106"
	"shared_preferences 2.5.5 c3025c5534b01739267eb7d76959bbc25a6d10f6988e1c2a3036940133dd10bf"
	"shared_preferences_android 2.4.23 e8d4762b1e2e8578fc4d0fd548cebf24afd24f49719c08974df92834565e2c53"
	"shared_preferences_foundation 2.5.6 4e7eaffc2b17ba398759f1151415869a34771ba11ebbccd1b0145472a619a64f"
	"shared_preferences_linux 2.4.1 580abfd40f415611503cae30adf626e6656dfb2f0cee8f465ece7b6defb40f2f"
	"shared_preferences_platform_interface 2.4.2 649dc798a33931919ea356c4305c2d1f81619ea6e92244070b520187b5140ef9"
	"shared_preferences_web 2.4.3 c49bd060261c9a3f0ff445892695d6212ff603ef3115edbb448509d407600019"
	"shared_preferences_windows 2.4.1 94ef0f72b2d71bc3e700e025db3710911bd51a71cefb65cc609dd0d9a982e3c1"
	"shelf 1.4.1 ad29c505aee705f41a4d8963641f91ac4cee3c8fad5947e033390a7bd8180fa4"
	"shelf 1.4.2 e7dd780a7ffb623c57850b33f43309312fc863fb6aa3d276a754bb299839ef12"
	"shelf_packages_handler 3.0.2 89f967eca29607c933ba9571d838be31d67f53f6e4ee15147d5dc2934fee1b1e"
	"shelf_static 1.1.2 a41d3f53c4adf0f57480578c1d61d90342cd617de7fc8077b1304643c2d85c1e"
	"shelf_static 1.1.3 c87c3875f91262785dade62d135760c2c69cb217ac759485334c5857ad89f6e3"
	"shelf_web_socket 1.0.4 9ca081be41c60190ebcb4766b2486a7d50261db7bd0f5d9615f2d653637a84c1"
	"shelf_web_socket 2.0.1 cc36c297b52866d203dbf9332263c94becc2fe0ceaa9681d07b6ef9807023b67"
	"shortid 0.1.2 d0b40e3dbb50497dad107e19c54ca7de0d1a274eb9b4404991e443dadb9ebedb"
	"slang 4.19.0 430749837528bb692b5ee03699fadab90d0d4a6dfbf42aab28e81df8da4c2fb8"
	"slang_build_runner 4.19.0 f2b6c5fc1f5bc41de80b05e95e7d5d03b5c3041082877ce931fc7ba61cd08afe"
	"slang_flutter 4.19.0 2348a39432c48d7c890a2a1e3409b9faae3e49f117fe56d390d4236de8d064f4"
	"source_gen 4.2.4 a603f1fb984a7391ae5978d1b92bfaaa08b350dca5c825256f925818f7943bf5"
	"source_map_stack_trace 2.1.1 84cf769ad83aa6bb61e0aa5a18e53aea683395f196a6f39c4c881fb90ed4f7ae"
	"source_map_stack_trace 2.1.2 c0713a43e323c3302c2abe2a1cc89aa057a387101ebd280371d6a6c9fa68516b"
	"source_maps 0.10.12 708b3f6b97248e5781f493b765c3337db11c5d2c81c3094f10904bfa8004c703"
	"source_maps 0.10.13 190222579a448b03896e0ca6eca5998fa810fda630c1d65e2f78b3f638f54812"
	"source_span 1.10.0 53e943d4206a5e30df338fd4c6e7a077e02254531b138a15aec3bd143c1a8b3c"
	"source_span 1.10.2 56a02f1f4cd1a2d96303c0144c93bd6d909eea6bee6bf5a0e0b685edbd4c47ab"
	"stack_trace 1.11.1 73713990125a6d93122541237550ee3352a2d84baad52d375a4cad2eb9b7ce0b"
	"stack_trace 1.12.1 8b27215b45d22309b5cddda1aa2b19bdfec9df0e765f2de506401c071d38d1b1"
	"stream_channel 2.1.2 ba2aa5d8cc609d96bbb2899c28934f9e1af5cddbd60a827822ea467161eb54e7"
	"stream_channel 2.1.4 969e04c80b8bcdf826f8f16579c7b14d780458bd97f56d107d3950fdbeef059d"
	"stream_transform 2.1.1 ad47125e588cfd37a9a7f86c7d6356dde8dfe89d071d293f80ca9e9273a33871"
	"string_scanner 1.2.0 556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
	"string_scanner 1.4.1 921cd31725b72fe181906c6a94d987c78e3b98c2e205b397ea399d4054872b43"
	"system_settings_2 3.0.2 8f8d1cb06dce3a0f1e432045dc3b06a311aea92468421bc00dba637a0fdf70f9"
	"term_glyph 1.2.1 a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84"
	"term_glyph 1.2.2 7f554798625ea768a7518313e58f83891c7f5024f88e46e7182a4558850a4b8e"
	"test 1.24.6 9b0dd8e36af4a5b1569029949d50a52cb2a2a2fdaa20cebb96e6603b9ae241f9"
	"test 1.30.0 280d6d890011ca966ad08df7e8a4ddfab0fb3aa49f96ed6de56e3521347a9ae7"
	"test_api 0.6.1 5c2f730018264d276c20e4f1503fd1308dfbbae39ec8ee63c5236311ac06954b"
	"test_api 0.7.10 8161c84903fd860b26bfdefb7963b3f0b68fee7adea0f59ef805ecca346f0c7a"
	"test_core 0.5.6 4bef837e56375537055fdbbbf6dd458b1859881f4c7e6da936158f77d61ab265"
	"test_core 0.6.16 0381bd1585d1a924763c308100f2138205252fb90c9d4eeaf28489ee65ccde51"
	"time 2.1.6 46187cf30bffdab28c56be9a63861b36e4ab7347bf403297595d6a97e10c789f"
	"toml 0.14.0 157c5dca5160fced243f3ce984117f729c788bb5e475504f3dbcda881accee44"
	"tray_manager 0.5.3 1a659b08baa6e9b91ef8ce16eda37740de398be1c4cf322b8a1ddfef25c68c5a"
	"type_plus 2.1.1 d5d1019471f0d38b91603adb9b5fd4ce7ab903c879d2fbf1a3f80a630a03fcc9"
	"typed_data 1.3.2 facc8d6582f16042dd49f2463ff1bd6e2c9ef9f3d5da3d9b087e244a7b564b3c"
	"typed_data 1.4.0 f9049c039ebfeb4cf7a7104a675823cd72dba8297f264b6637062516699fa006"
	"universal_platform 1.1.0 64e16458a0ea9b99260ceb5467a214c1f298d647c659af1bff6d3bf82536b1ec"
	"uri_content 3.1.1 b1de935b89677192282f312188aa07e8f96df91daa735f19f6404aa781b5141e"
	"url_launcher 6.3.2 f6a7e5c4835bb4e3026a04793a4199ca2d14c739ec378fdfe23fc8075d0439f8"
	"url_launcher_android 6.3.30 17bc677f0b301615530dd1d67e0a9828cafa2d0b6b6eae4cd3679b7eac4a273c"
	"url_launcher_ios 6.4.1 580fe5dfb51671ae38191d316e027f6b76272b026370708c2d898799750a02b0"
	"url_launcher_linux 3.2.2 d5e14138b3bc193a0f63c10a53c94b91d399df0512b1f29b94a043db7482384a"
	"url_launcher_macos 3.2.5 368adf46f71ad3c21b8f06614adb38346f193f3a59ba8fe9a2fd74133070ba18"
	"url_launcher_platform_interface 2.3.2 552f8a1e663569be95a8190206a38187b531910283c3e982193e4f2733f01029"
	"url_launcher_web 2.4.3 85c81589622fbc87c1c683aaea164d3604a7777495a79d91e39ffcdec39ddb34"
	"url_launcher_windows 3.1.5 712c70ab1b99744ff066053cbe3e80c73332b38d46e5e945c98689b2e66fc15f"
	"uuid 4.6.0 9b129329f58692f6e6578329498a8fe9fbe98f090beb764ffbb8ee2eadd01dcd"
	"vector_graphics_codec 1.1.13 99fd9fbd34d9f9a32efd7b6a6aae14125d8237b10403b422a6a6dfeac2806146"
	"vector_graphics_compiler 1.3.0 4dca4feb77dc3ec7f6e27e49c53241eb8217f55e4f9b12599a27f8903bca5682"
	"vector_math 2.2.0 d530bd74fea330e6e364cda7a85019c434070188383e1cd8d9777ee586914c5b"
	"version 3.0.0 2307e23a45b43f96469eeab946208ed63293e8afca9c28cd8b5241ff31c55f55"
	"video_player 2.11.1 48a7bdaa38a3d50ec10c78627abdbfad863fdf6f0d6e08c7c3c040cfd80ae36f"
	"video_player_android 2.9.5 877a6c7ba772456077d7bfd71314629b3fe2b73733ce503fc77c3314d43a0ca0"
	"video_player_avfoundation 2.11.0 c238f5f0a26845cd0bcc2956049b63065a4d3c40ddfc22c3414cd170bef7fff9"
	"video_player_platform_interface 6.9.0 92c0fbabe20c788e71fd10d26cea998d0d253282e65d145aed0818731cf593ce"
	"video_player_web 2.4.0 9f3c00be2ef9b76a95d94ac5119fb843dca6f2c69e6c9968f6f2b6c9e7afbdeb"
	"visibility_detector 0.4.0+2 dd5cc11e13494f432d15939c3aa8ae76844c42b723398643ce9addb88a5ed420"
	"vm_service 11.9.0 0fae432c85c4ea880b33b497d32824b97795b04cdaa74d270219572a1f50268d"
	"vm_service 15.2.0 0016aef94fc66495ac78af5859181e3f3bf2026bd8eecc72b9565601e19ab360"
	"wakelock_plus 1.5.2 ddf3db70eaa10c37558ff817519b85d527dbd21034fd5d8e1c2e85f31588f1c1"
	"wakelock_plus_platform_interface 1.6.0 0618d1799f0b28bcf98255b4ee8313e6fc4d38589dc4ee5fe5840d57d1aff6da"
	"watcher 1.1.0 3d2ad6751b3c16cf07c7fca317a1413b3f26530319181b37e3b9039b84fc01d8"
	"watcher 1.2.1 1398c9f081a753f9226febe8900fce8f7d0a67163334e1c94a2438339d79d635"
	"web 1.1.1 868d88a33d8a87b18ffc05f9f030ba328ffefba92d6c127917a2ba740f9cfe4a"
	"web_socket 1.0.1 34d64019aa8e36bf9842ac014bb5d2f5586ca73df5e4d9bf5c936975cae6982c"
	"web_socket_channel 2.4.0 d88238e5eac9a42bb43ca4e721edba3c08c6354d4a53063afaa568516217621b"
	"web_socket_channel 3.0.3 d645757fb0f4773d602444000a8131ff5d48c9e47adfe9772652dd1a4f2d45c8"
	"webkit_inspection_protocol 1.2.0 67d3a8b6c79e1987d19d848b0892e582dbb0c66c57cc1fef58a177dd2aa2823d"
	"webkit_inspection_protocol 1.2.1 87d3f2333bb240704cd3f1c6b5b7acd8a10e7f0bc28c28dcf14e782014f4a572"
	"wechat_assets_picker 10.1.3 ccd92f3e8c968e2cbad939bce82b454e798a7669c1e4ab74e871822ce2440b2d"
	"wechat_picker_library 1.0.7 5cb61b9aa935b60da5b043f8446fbb9c5077419f20ccc4856bf444aec4f44bc1"
	"win32 5.15.0 d7cb55e04cd34096cd3a79b3330245f54cb96a370a1c27adb3c84b917de8b08e"
	"win32_registry 2.1.0 6f1b564492d0147b330dd794fee8f512cec4977957f310f9951b5f9d83618dae"
	"window_manager 0.5.2 05c231fd7b23d2380f14c5cc10b7b93d60d4fa4a2fb4e0f032de27e44b5560e9"
	"windows_taskbar 1.1.2 204edfdb280a7053febdf50fc9b49b3c007255bd8a83c082d10c174ec6548f33"
	"xdg_directories 1.1.0 7a3f37b05d989967cdddcbb571f1ea834867ae2faa29725fd085180e0883aa15"
	"xml 7.0.1 67f0aff7be013d107995e9b75bf4e7f2c3ef2dfdb2c8e68024bba0a7fd5756a4"
	"yaml 3.1.2 75769501ea3489fca56601ff33454fe45507ea3bfb014161abc3b43ae25989d5"
	"yaml 3.1.3 b9da305ac7c39faa3f030eccd175340f968459dae4af175130b3fc47e40d76ce"
	"yaru 10.2.0 95e801c52dfda458bcb772baee6b2575c711fd951616a24910d6d30e70f5fb0d"
	"yaru_window 0.2.2 58539a9abe9901891dadce142c7a5d303920b780dd0f7bd21f076a80adeeb744"
	"yaru_window_linux 0.2.2 885ad0ba5832d350c42862ce02da478599ef550280eb7f6b15285481fcff6f53"
	"yaru_window_manager 0.1.3 6288fd6ccd8bb9d5be56073c6f277e2da08dd38e346507bf88bc9332b08dd180"
	"yaru_window_platform_interface 0.1.3 d514387cc96750112ecf1933b6f12a1912beca199178d00052c0e87a94e232fa"
	"yaru_window_web 0.0.4 cf4d79e0760fbdcb78d4bbca3b5563f99518629224b9e5611f0ebd592befe1d9"
)
PUB_GIT=(
	"device_apps https://github.com/Tienisto/device_apps.git 5dc7956d938541254d2e175766b3b84ea38bb85b ."
	"pasteboard https://github.com/Seidko/flutter-plugins.git 58748dae405df5e68a131e4905d48e75d0624be2 packages/pasteboard"
	"permission_handler_windows https://github.com/localsend/permission_handler_windows_noop.git 2dadd8afbf81e0e3e4791d7144e689555e58f649 ."
)

SRC_URI="
	https://github.com/localsend/localsend/archive/refs/tags/v${PV}.tar.gz
		-> ${P}.tar.gz
	https://github.com/gentoo-zh-drafts/localsend/releases/download/v${PV}/${P}-crates.tar.xz
	$(dart-pub_src_uri)
"
S="${WORKDIR}/${P}/app"

LICENSE="Apache-2.0"
# bundled Dart packages
LICENSE+=" BSD MIT MPL-2.0"
# the Flutter engine copied in bundles ICU, HarfBuzz, Skia, FreeType,
# libjpeg-turbo, expat, libpng, libwebp, zlib and more
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions Boost-1.0 FTL IJG ISC MIT MPL-2.0
	Old-MIT Unicode-3.0 Unicode-DFS-2016 ZLIB libpng public-domain
"
# Dependent crate licenses
LICENSE+="
	0BSD Apache-2.0-with-LLVM-exceptions BSD BSD-1 BSD-2 Boost-1.0 CC0-1.0
	CDLA-Permissive-2.0 ISC LGPL-2.1+ Unicode-3.0 Unicode-DFS-2016 Unlicense
	WTFPL-2 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

QA_PRESTRIPPED="opt/${PN}/lib/libflutter_linux_gtk.so"
QA_PREBUILT="opt/${PN}/lib/libflutter_linux_gtk.so"

DEPEND="
	app-accessibility/at-spi2-core:2
	dev-libs/glib:2
	dev-libs/libayatana-appindicator
	media-libs/fontconfig
	media-libs/libepoxy
	x11-libs/cairo
	x11-libs/gdk-pixbuf:2
	x11-libs/gtk+:3
	x11-libs/pango
"
RDEPEND="
	${DEPEND}
	x11-misc/xdg-user-dirs
	x11-misc/xdg-utils
	!net-misc/localsend-bin
"
BDEPEND="
	${FLUTTER_DEPEND}
	dev-util/patchelf
"

pkg_setup() {
	llvm-r2_pkg_setup
	rust_pkg_setup
}

src_unpack() {
	flutter-app_src_unpack
	cargo_gen_config
}

src_prepare() {
	pushd "${WORKDIR}"/${P} >/dev/null || die
	# cargokit is the Rust build driver flutter_rust_bridge vendors into the tree
	eapply "${FILESDIR}"/${P}-cargokit-offline.patch
	# drops the in-app purchase code; the script cd's into app/ itself
	sh support/scripts/remove_proprietary_dependencies.sh || die
	popd >/dev/null || die

	flutter-app_src_prepare
	flutter-app_pub_get

	# upstream ships neither the generated localisations nor the data classes
	dart run build_runner build --delete-conflicting-outputs || die
}

src_compile() {
	cargo_env flutter-app_src_compile
}

src_test() {
	flutter-app_setup_env
	flutter --no-version-check test --no-pub || die
	pushd "${WORKDIR}"/${P}/packages/localsend_isolates >/dev/null || die
	flutter --no-version-check test --no-pub || die
	popd >/dev/null || die

	# the tests live in the core crate the plugin links, run the way
	# upstream's CI does
	cargo_src_test --features full \
		--manifest-path "${WORKDIR}"/${P}/packages/core/Cargo.toml
}

src_install() {
	local bundle
	bundle=$(flutter-app_bundle_dir)

	insinto /opt/${PN}
	doins -r "${bundle}"/{data,lib}
	exeinto /opt/${PN}
	doexe "${bundle}"/${PN}_app

	# every plugin keeps the ephemeral build directory as its RUNPATH
	local plugin
	for plugin in "${ED}"/opt/${PN}/lib/lib*plugin.so; do
		[[ -e ${plugin} ]] || continue
		patchelf --set-rpath '$ORIGIN' "${plugin}" || die
	done

	dodir /opt/bin
	dosym -r /opt/${PN}/${PN}_app /opt/bin/${PN}

	newicon -s 128 assets/img/logo-128.png ${PN}.png
	newicon -s 256 assets/img/logo-256.png ${PN}.png
	domenu "${FILESDIR}"/${PN}.desktop
}
