# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# @ECLASS: dart-pub.eclass
# @MAINTAINER:
# Zakk <zakk@gentoozh.org>
# @SUPPORTED_EAPIS: 8
# @BLURB: build a pub cache from individually fetched Dart packages
# @DESCRIPTION:
# pub resolves a Dart project against a cache of unpacked packages.  Instead of
# shipping that cache as one prebuilt tarball, an ebuild lists the packages
# pubspec.lock resolved in PUB_HOSTED and PUB_GIT, and this eclass turns them
# into SRC_URI entries that portage fetches and verifies like any other
# distfile.  scripts/pubspec2ebuild.py writes both arrays from a lockfile.
#
# @EXAMPLE:
# @CODE
# EAPI=8
#
# inherit dart-pub
#
# # generated by scripts/pubspec2ebuild.py
# PUB_HOSTED=(
#	"args 2.6.0 bf9f5caeea8d8fe6721a9c358dd8a5c1947b27f1cfaa18b39c301273594919e6"
# )
#
# SRC_URI="
#	https://example.org/${P}.tar.gz
#	$(dart-pub_src_uri)
# "
#
# src_prepare() {
#	default
#	dart-pub_git_overrides "${S}"
# }
# @CODE

case ${EAPI} in
	8) ;;
	*) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
esac

if [[ -z ${_DART_PUB_ECLASS} ]]; then
_DART_PUB_ECLASS=1

# @ECLASS_VARIABLE: PUB_HOSTED
# @DEFAULT_UNSET
# @DESCRIPTION:
# Array of pub.dev packages, one "<name> <version> <sha256>" entry each, as
# resolved by pubspec.lock.  pub reads the digest back out of the cache, so it
# has to be recorded even though portage verifies the download itself.

# @ECLASS_VARIABLE: PUB_GIT
# @DEFAULT_UNSET
# @DESCRIPTION:
# Array of git-sourced packages, one "<name> <url> <commit> <subpath>" entry
# each.  <subpath> is the package's directory inside the repository, or "." when
# the repository is the package.  Only GitHub is supported: the commit is
# fetched as a GitHub archive, and pubspec2ebuild.py rejects any other host.

# @ECLASS_VARIABLE: EPUB_CACHE
# @DESCRIPTION:
# Directory dart-pub_src_unpack builds the pub cache in.  Defaults to
# ${WORKDIR}/pub-cache.  Set PUB_CACHE to it before running pub; an ebuild may
# point this elsewhere after inherit.
EPUB_CACHE="${WORKDIR}/pub-cache"

# @ECLASS_VARIABLE: EPUB_GIT_DIR
# @DESCRIPTION:
# Directory the PUB_GIT packages are unpacked into, one per package.  Defaults
# to ${WORKDIR}/pub-git.
EPUB_GIT_DIR="${WORKDIR}/pub-git"

# @FUNCTION: dart-pub_src_uri
# @RETURN: one SRC_URI entry per package in PUB_HOSTED and PUB_GIT
# @DESCRIPTION:
# Every distfile is renamed with a dart- prefix: pub package names such as
# "test", "path" and "async" would otherwise collide in the shared DISTDIR.
dart-pub_src_uri() {
	# global scope, so split with set -- rather than a here-string, which may
	# write a temporary file
	local entry

	for entry in "${PUB_HOSTED[@]}"; do
		set -- ${entry}
		echo "https://pub.dev/api/archives/${1}-${2}.tar.gz -> dart-${1}-${2}.tar.gz"
	done

	for entry in "${PUB_GIT[@]}"; do
		set -- ${entry}
		[[ ${2} == https://github.com/* ]] ||
			die "${ECLASS}: PUB_GIT only supports GitHub, got ${2}"
		echo "${2%.git}/archive/${3}.tar.gz -> dart-${1}-${3}.gh.tar.gz"
	done
}

# @FUNCTION: dart-pub_populate
# @USAGE: <cache-dir>
# @DESCRIPTION:
# Unpack every PUB_HOSTED package into <cache-dir> in the layout pub expects:
# hosted/pub.dev/<name>-<version>/, with the archive digest recorded alongside
# so pub accepts the cache as one it wrote itself.
dart-pub_populate() {
	[[ ${#} -eq 1 ]] || die "${FUNCNAME}: takes exactly one argument: <cache-dir>"

	local cache=${1}
	local hosted=${cache}/hosted/pub.dev
	local hashes=${cache}/hosted-hashes/pub.dev
	mkdir -p "${hosted}" "${hashes}" || die

	local entry name version sha256
	for entry in "${PUB_HOSTED[@]}"; do
		read -r name version sha256 <<<"${entry}"
		mkdir -p "${hosted}/${name}-${version}" || die
		tar -xf "${DISTDIR}/dart-${name}-${version}.tar.gz" \
			-C "${hosted}/${name}-${version}" || die
		printf '%s' "${sha256}" > "${hashes}/${name}-${version}.sha256" || die
	done
}

# @FUNCTION: _dart-pub_unpack_git
# @INTERNAL
# @DESCRIPTION:
# Unpack every PUB_GIT package into EPUB_GIT_DIR.
_dart-pub_unpack_git() {
	local entry name url commit subpath
	for entry in "${PUB_GIT[@]}"; do
		read -r name url commit subpath <<<"${entry}"
		mkdir -p "${EPUB_GIT_DIR}/${name}" || die
		tar -xf "${DISTDIR}/dart-${name}-${commit}.gh.tar.gz" \
			-C "${EPUB_GIT_DIR}/${name}" --strip-components=1 || die
	done
}

# @FUNCTION: dart-pub_src_unpack
# @DESCRIPTION:
# Unpack the distfiles that are not Dart packages, then lay the Dart packages
# out: the hosted ones as a pub cache in EPUB_CACHE, the git ones in
# EPUB_GIT_DIR.
dart-pub_src_unpack() {
	local -A pubfiles=()
	local entry

	for entry in "${PUB_HOSTED[@]}"; do
		set -- ${entry}
		pubfiles["dart-${1}-${2}.tar.gz"]=1
	done
	for entry in "${PUB_GIT[@]}"; do
		set -- ${entry}
		pubfiles["dart-${1}-${3}.gh.tar.gz"]=1
	done

	local archive
	for archive in ${A}; do
		[[ -n ${pubfiles[${archive}]} ]] || unpack "${archive}"
	done

	dart-pub_populate "${EPUB_CACHE}"
	_dart-pub_unpack_git
}

# @FUNCTION: dart-pub_git_overrides
# @USAGE: <project-dir>
# @DESCRIPTION:
# Write a pubspec_overrides.yaml in <project-dir> pointing every PUB_GIT
# package at its unpacked directory.  This resolves the git dependencies, and
# any git dependency_overrides the project already declares, without pub
# reconstructing its internal git cache.
dart-pub_git_overrides() {
	[[ ${#} -eq 1 ]] || die "${FUNCNAME}: takes exactly one argument: <project-dir>"
	[[ ${#PUB_GIT[@]} -gt 0 ]] || return 0

	local projdir=${1}
	local overrides=${projdir}/pubspec_overrides.yaml

	# merging arbitrary YAML is out of scope, and overwriting would drop the
	# project's own overrides without a trace
	[[ -e ${overrides} ]] &&
		die "${FUNCNAME}: ${overrides} already exists, merge it in the ebuild"

	echo "dependency_overrides:" > "${overrides}" || die

	local entry name url commit subpath path
	for entry in "${PUB_GIT[@]}"; do
		read -r name url commit subpath <<<"${entry}"
		path=${EPUB_GIT_DIR}/${name}
		[[ ${subpath} == . ]] || path+=/${subpath}
		printf '  %s:\n    path: %s\n' "${name}" "${path}" >> "${overrides}" || die
	done
}

fi

EXPORT_FUNCTIONS src_unpack
