# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# @ECLASS: flutter-app.eclass
# @MAINTAINER:
# Zakk <zakk@gentoozh.org>
# @SUPPORTED_EAPIS: 8
# @PROVIDES: dart-pub llvm-r2 ninja-utils
# @BLURB: build a Flutter application against dev-util/flutter-bin
# @DESCRIPTION:
# The Flutter SDK writes to its own tree: flutter_tools takes a lock on
# bin/cache/lockfile and resolves its dependencies into
# packages/flutter_tools/.dart_tool.  It therefore cannot build from the
# read-only install, and this eclass copies dev-util/flutter-bin into WORKDIR
# instead.  Everything but "flutter --version" needs those dependencies
# resolved, so dev-util/flutter-bin ships them in the SDK's own pub cache and
# flutter-app_pub_get resolves them offline.
#
# flutter_tools builds the Linux target with CC=clang, so LLVM_COMPAT has to be
# set the same way as for any other clang consumer.
#
# @EXAMPLE:
# @CODE
# EAPI=8
#
# LLVM_COMPAT=( 18 19 20 21 22 )
# FLUTTER_PV="3.24.5"
#
# inherit flutter-app
#
# # generated by pubspec2ebuild from pubspec.lock
# PUB_HOSTED=(
#	"args 2.6.0 bf9f5caeea8d8fe6721a9c358dd8a5c1947b27f1cfaa18b39c301273594919e6"
# )
#
# SRC_URI="
#	https://example.org/${P}.tar.gz
#	$(dart-pub_src_uri)
# "
#
# BDEPEND="${FLUTTER_DEPEND}"
#
# # with cargo.eclass: unpack once here, then let cargo write its config
# src_unpack() {
#	flutter-app_src_unpack
#	cargo_gen_config
# }
#
# src_prepare() {
#	flutter-app_src_prepare
#	flutter-app_pub_get
# }
#
# src_install() {
#	local bundle
#	bundle=$(flutter-app_bundle_dir)
#
#	insinto /opt/${PN}
#	doins -r "${bundle}"/.
# }
# @CODE

case ${EAPI} in
	8) ;;
	*) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
esac

if [[ -z ${_FLUTTER_APP_ECLASS} ]]; then
_FLUTTER_APP_ECLASS=1

# @ECLASS_VARIABLE: FLUTTER_PV
# @REQUIRED
# @PRE_INHERIT
# @DESCRIPTION:
# Slot of dev-util/flutter-bin to build against, which is its version.  A
# Flutter project pins the SDK it is built with; read it out of the project's
# CI workflow.

[[ -n ${FLUTTER_PV} ]] || die "${ECLASS}: FLUTTER_PV must be set before inherit"

# @ECLASS_VARIABLE: EFLUTTER_ROOT
# @DESCRIPTION:
# The writable copy of the SDK that flutter-app_setup_sdk creates.  Defaults to
# ${WORKDIR}/flutter; a value set before inherit is kept.
: "${EFLUTTER_ROOT:=${WORKDIR}/flutter}"

# @ECLASS_VARIABLE: EPUB_CACHE
# @DESCRIPTION:
# Defaults to the cache inside the SDK copy instead of dart-pub.eclass'
# ${WORKDIR}/pub-cache: dev-util/flutter-bin ships flutter_tools' own packages
# there, and the application's packages are added to the same cache.  A value
# set before inherit is kept.
: "${EPUB_CACHE:=${EFLUTTER_ROOT}/.pub-cache}"

inherit dart-pub llvm-r2 ninja-utils

# @ECLASS_VARIABLE: FLUTTER_APP_DIR
# @DEFAULT_UNSET
# @DESCRIPTION:
# Directory holding the application's pubspec.yaml.  Unset means S.

# @ECLASS_VARIABLE: FLUTTER_DEPEND
# @OUTPUT_VARIABLE
# @DESCRIPTION:
# Everything a Flutter Linux build needs at build time.  Add it to BDEPEND, the
# way rust.eclass' RUST_DEPEND is used.  flutter_tools compiles native assets
# with the clang, ld.lld and llvm-ar it finds next to the clang++ on PATH.
FLUTTER_DEPEND="
	${NINJA_DEPEND}
	dev-build/cmake
	dev-vcs/git
	dev-util/flutter-bin:${FLUTTER_PV}
	virtual/pkgconfig
	$(llvm_gen_dep '
		llvm-core/clang:${LLVM_SLOT}
		llvm-core/lld:${LLVM_SLOT}
		llvm-core/llvm:${LLVM_SLOT}
	')
"

# @FUNCTION: flutter-app_setup_sdk
# @DESCRIPTION:
# Copy dev-util/flutter-bin to EFLUTTER_ROOT and make it writable.  reflink
# makes the copy free on a CoW filesystem and falls back to a real copy.
flutter-app_setup_sdk() {
	cp -a --reflink=auto "${BROOT}"/opt/flutter-bin-${FLUTTER_PV} "${EFLUTTER_ROOT}" || die
	chmod -R u+w "${EFLUTTER_ROOT}" || die
}

# @FUNCTION: flutter-app_src_unpack
# @DESCRIPTION:
# Set the SDK up, then run dart-pub_src_unpack, which unpacks every distfile
# that is not a Dart package, a crate tarball included.  An ebuild that also
# inherits cargo calls cargo_gen_config after this instead of
# cargo_src_unpack, so nothing is unpacked twice.
flutter-app_src_unpack() {
	flutter-app_setup_sdk
	dart-pub_src_unpack
}

# @FUNCTION: flutter-app_setup_env
# @DESCRIPTION:
# Export what flutter and dart read: the SDK copy on PATH and the pub cache.
# flutter reads the SDK version with git, which refuses to work in a tree the
# calling user does not own, so safe.directory is appended to whatever
# command-scope git configuration the ebuild already set.
flutter-app_setup_env() {
	export PATH="${EFLUTTER_ROOT}/bin:${EFLUTTER_ROOT}/bin/cache/dart-sdk/bin:${PATH}"
	export PUB_CACHE="${EPUB_CACHE}"
	export FLUTTER_SUPPRESS_ANALYTICS=true

	if [[ -z ${_FLUTTER_APP_SAFE_DIRECTORY} ]]; then
		local index=${GIT_CONFIG_COUNT:-0}
		export "GIT_CONFIG_KEY_${index}=safe.directory"
		export "GIT_CONFIG_VALUE_${index}=${EFLUTTER_ROOT}"
		export GIT_CONFIG_COUNT=$(( index + 1 ))
		_FLUTTER_APP_SAFE_DIRECTORY=1
	fi
}

# @FUNCTION: flutter-app_pub_get
# @USAGE: [extra pub arguments]
# @DESCRIPTION:
# Point the application at its PUB_GIT packages, then resolve flutter_tools'
# dependencies and the application's, both offline.  pub keeps the versions
# recorded in pubspec.lock when the cache holds them; --enforce-lockfile is not
# passed because the git dependencies become path dependencies, which never
# match the lockfile.
flutter-app_pub_get() {
	flutter-app_setup_env

	pushd "${EFLUTTER_ROOT}/packages/flutter_tools" >/dev/null || die
	dart pub get --offline || die
	popd >/dev/null || die

	dart-pub_git_overrides "${FLUTTER_APP_DIR:-${S}}"

	pushd "${FLUTTER_APP_DIR:-${S}}" >/dev/null || die
	flutter --no-version-check pub get --offline "$@" || die
	popd >/dev/null || die
}

# @FUNCTION: flutter-app_src_prepare
# @DESCRIPTION:
# Apply patches, then take the -Werror and the fixed -O3 out of the Linux
# runner's CMakeLists.txt.  Both come from Flutter's project template, so
# every application carries them.
flutter-app_src_prepare() {
	default

	local cmakelists=${FLUTTER_APP_DIR:-${S}}/linux/CMakeLists.txt
	grep -q -- '-Wall -Werror)' "${cmakelists}" &&
		grep -q ':-O3>")' "${cmakelists}" ||
		die "${cmakelists} does not carry the template's compile options"
	sed -i \
		-e 's/ -Wall -Werror)/ -Wall)/' \
		-e '/:-O3>")$/d' \
		"${cmakelists}" || die
}

# @FUNCTION: flutter-app_src_compile
# @USAGE: [extra flutter build arguments]
# @DESCRIPTION:
# Build the release bundle.  The packages are already resolved, so pub is not
# allowed to run again.  flutter hands CMake a Release build type and runs
# ninja itself: a toolchain file empties the flags CMake adds for that build
# type, so the user's CFLAGS stand, and a ninja wrapper carries the job
# count.  gen_snapshot is told not to strip the AOT snapshot; Portage does
# that, keeping the debug symbols when asked to.
flutter-app_src_compile() {
	flutter-app_setup_env

	cat > "${T}"/flutter-app-toolchain.cmake <<-EOF || die
		set(CMAKE_C_FLAGS_RELEASE "" CACHE STRING "")
		set(CMAKE_CXX_FLAGS_RELEASE "" CACHE STRING "")
	EOF
	local -x CMAKE_TOOLCHAIN_FILE=${T}/flutter-app-toolchain.cmake

	local ninja
	ninja=$(type -P ninja) || die "ninja not found"
	mkdir -p "${T}"/flutter-app-bin || die
	cat > "${T}"/flutter-app-bin/ninja <<-EOF || die
		#!/bin/sh
		exec ${ninja} $(get_NINJAOPTS) "\$@"
	EOF
	chmod +x "${T}"/flutter-app-bin/ninja || die
	local -x PATH=${T}/flutter-app-bin:${PATH}

	pushd "${FLUTTER_APP_DIR:-${S}}" >/dev/null || die
	flutter --no-version-check build linux --release --no-pub \
		--extra-gen-snapshot-options=--no-strip "$@" || die
	popd >/dev/null || die
}

# @FUNCTION: flutter-app_bundle_dir
# @RETURN: path of the bundle flutter-app_src_compile produced
# @DESCRIPTION:
# Echo where flutter wrote the release bundle for this architecture.
flutter-app_bundle_dir() {
	local target
	case ${ARCH} in
		amd64) target=x64 ;;
		arm64) target=arm64 ;;
		*) die "${ECLASS}: no Flutter Linux target for ARCH=${ARCH}" ;;
	esac

	echo "${FLUTTER_APP_DIR:-${S}}/build/linux/${target}/release/bundle"
}

fi

EXPORT_FUNCTIONS src_unpack src_prepare src_compile
